export const UPDATE_SOLUTION = 'UPDATE_SOLUTION';
export const UPDATE_TURN = 'UPDATE_TURN';
export const UPDATE_CURRENT_GUESS = 'UPDATE_CURRENT_GUESS';
export const UPDATE_ATTEMPTED_WORDLES = 'UPDATE_ATTEMPTED_WORDLES';
export const UPDATE_HISTORY = 'UPDATE_HISTORY';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
